const enum ROUTES {
  SSM_UPDATE_ENVIRONMENT_REQUEST,
  SSM_SEND_COMMAND_STATUS_REQUEST,
  MESSAGE_WITH_JIRA_TICKET,
  NET_SUITE_JOB,
  PLAYGROUND_BUSYBOX_JOB,
  SLACK_URL_VALIDATION,
  SLACK_SEND_MESSAGE_REQUEST,
  CICD_APPROVAL_REQUEST,
  CICD_APPROVAL_RESPONSE,
  FROM_BOT,
  REGULAR_MESSAGE,
  APP_MENTION,
  UNKNOWN
}
